

#mybeautystat.myshopify.com

# Admin API access token
# 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

# API key and secret key
# API key
# 49b37c461f408bf99781594ce19b14a8

# API secret key
# 0d863950293a305fa771648de582bdfb